apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-tuned
roleRef:
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: sa-tuned
  namespace: tuned
userNames:
- system:serviceaccount:tuned:sa-tuned
